import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Download, FileArchive, FileImage, FileText, LoaderCircle, Trash2, UploadCloud } from 'lucide-react'
import { useRef, useState, type DragEvent } from 'react'
import { toast } from 'sonner'
import { useAuth } from '../../contexts/AuthContext'
import { fileSize, messageFromError, timeAgo } from '../../lib/utils'
import { fileService } from '../../services/file'
import type { ProjectFile } from '../../types'
import { Button } from '../ui/Button'
import { EmptyState, ErrorState, LoadingState } from '../ui/States'

function FileIcon({ name }: { name: string }) { const ext = name.split('.').pop()?.toLowerCase(); if (['png','jpg','jpeg'].includes(ext || '')) return <FileImage className="size-5 text-fuchsia-500"/>; if (ext === 'zip') return <FileArchive className="size-5 text-amber-500"/>; return <FileText className="size-5 text-brand-500"/> }
export function FileRepository({ projectId, workspaceId, canManage }: { projectId: string; workspaceId: string; canManage: boolean }) {
  const { user } = useAuth(); const queryClient = useQueryClient(); const input = useRef<HTMLInputElement>(null); const [dragging, setDragging] = useState(false); const [progress, setProgress] = useState<number | null>(null)
  const query = useQuery({ queryKey: ['files', projectId], queryFn: () => fileService.list(projectId) })
  const upload = async (files: FileList | File[]) => { if (!user) return; for (const file of Array.from(files)) { try { setProgress(0); await fileService.upload(file, projectId, workspaceId, user.id, setProgress); toast.success(`${file.name} uploaded`); await queryClient.invalidateQueries({ queryKey: ['files', projectId] }) } catch (error) { toast.error(messageFromError(error)) } finally { setProgress(null) } } }
  const drop = (event: DragEvent) => { event.preventDefault(); setDragging(false); void upload(event.dataTransfer.files) }
  const remove = async (file: ProjectFile) => { if (!confirm(`Delete ${file.file_name}? This cannot be undone.`)) return; try { await fileService.remove(file); await queryClient.invalidateQueries({ queryKey: ['files', projectId] }); toast.success('File deleted') } catch (error) { toast.error(messageFromError(error)) } }
  if (query.isLoading) return <LoadingState label="Loading project files…"/>; if (query.error) return <ErrorState message={messageFromError(query.error)} retry={() => void query.refetch()}/>
  return <div className="space-y-5"><div onDragOver={(e) => { e.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={drop} className={`rounded-2xl border-2 border-dashed p-7 text-center transition ${dragging ? 'border-brand-500 bg-brand-50 dark:bg-brand-500/10' : 'border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900'}`}><input ref={input} type="file" multiple className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg,.zip,.txt" onChange={(event) => event.target.files && void upload(event.target.files)}/>{progress === null ? <><UploadCloud className="mx-auto mb-3 size-8 text-brand-500"/><p className="font-semibold">Drop files here or <button className="text-brand-600 hover:underline" onClick={() => input.current?.click()}>browse</button></p><p className="subtle mt-1">PDF, Office, images, ZIP, or TXT · up to 25 MB</p></> : <><LoaderCircle className="mx-auto mb-3 size-7 animate-spin text-brand-500"/><p className="font-semibold">Uploading… {progress}%</p><div className="mx-auto mt-3 h-2 max-w-xs overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-brand-500 transition-all" style={{ width: `${progress}%` }}/></div></>}</div>{query.data?.length ? <div className="overflow-hidden rounded-2xl border bg-white dark:bg-slate-900"><div className="hidden grid-cols-[1fr_110px_150px_100px] gap-4 border-b bg-slate-50 px-5 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500 dark:bg-slate-950 sm:grid"><span>File</span><span>Size</span><span>Uploaded</span><span className="text-right">Actions</span></div>{query.data.map((file) => <div key={file.id} className="grid gap-3 border-b p-4 last:border-0 sm:grid-cols-[1fr_110px_150px_100px] sm:items-center sm:gap-4 sm:px-5"><div className="flex min-w-0 items-center gap-3"><span className="rounded-xl bg-slate-100 p-2 dark:bg-slate-800"><FileIcon name={file.file_name}/></span><div className="min-w-0"><p className="truncate text-sm font-medium">{file.file_name}</p><p className="text-xs text-slate-500 sm:hidden">{fileSize(file.file_size)} · {timeAgo(file.created_at)}</p></div></div><span className="hidden text-sm text-slate-500 sm:block">{fileSize(file.file_size)}</span><div className="hidden sm:block"><p className="truncate text-sm">{file.uploader?.full_name || file.uploader?.username}</p><p className="text-xs text-slate-500">{timeAgo(file.created_at)}</p></div><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" aria-label="Download file" onClick={() => void fileService.download(file)}><Download className="size-4"/></Button>{(file.uploaded_by === user?.id || canManage) && <Button size="icon" variant="ghost" aria-label="Delete file" onClick={() => void remove(file)}><Trash2 className="size-4 text-red-500"/></Button>}</div></div>)}</div> : <EmptyState title="No project files yet" description="Upload briefs, designs, spreadsheets, and anything else your team needs."/>}</div>
}
