-- Username/password authentication keeps Supabase's required email identifier private.
-- Existing profiles retain their original authentication method; new username accounts
-- use the internal username@users.taskhub.internal identifier generated by the client.
create or replace function public.protect_immutable_fields() returns trigger language plpgsql set search_path = '' as $$
begin
  if tg_table_name = 'workspaces' and new.owner_id <> old.owner_id then raise exception 'Workspace ownership cannot be changed'; end if;
  if tg_table_name = 'profiles' and (new.email <> old.email or new.username <> old.username) then raise exception 'Profile identity is managed by authentication'; end if;
  return new;
end $$;
